In [14]:
import pandas as pd
import numpy as np
school = pd.read_csv('2016 School Explorer.csv')
shsat = pd.read_csv('D5 SHSAT Registrations and Testers.csv')

In [20]:
school = pd.DataFrame(school)
shsat = pd.DataFrame(shsat)

In [22]:
school.shape

(1272, 161)

In [ ]:
df

In [6]:
school

,Adjusted Grade,New?,Other Location Code in LCGMS,School Name,SED Code,Location Code,District,Latitude,Longitude,Address (Full),...,Grade 8 Math - All Students Tested,Grade 8 Math 4s - All Students,Grade 8 Math 4s - American Indian or Alaska Native,Grade 8 Math 4s - Black or African American,Grade 8 Math 4s - Hispanic or Latino,Grade 8 Math 4s - Asian or Pacific Islander,Grade 8 Math 4s - White,Grade 8 Math 4s - Multiracial,Grade 8 Math 4s - Limited English Proficient,Grade 8 Math 4s - Economically Disadvantaged
0,NaN,NaN,NaN,P.S. 015 ROBERTO CLEMENTE,310100010015,01M015,1,40.721834,-73.978766,"333 E 4TH ST NEW YORK, NY 10009",...,0,0,0,0,0,0,0,0,0,0
1,NaN,NaN,NaN,P.S. 019 ASHER LEVY,310100010019,01M019,1,40.729892,-73.984231,"185 1ST AVE NEW YORK, NY 10003",...,0,0,0,0,0,0,0,0,0,0
2,NaN,NaN,NaN,P.S. 020 ANNA SILVER,310100010020,01M020,1,40.721274,-73.986315,"166 ESSEX ST NEW YORK, NY 10002",...,0,0,0,0,0,0,0,0,0,0
3,NaN,NaN,NaN,P.S. 034 FRANKLIN D. ROOSEVELT,310100010034,01M034,1,40.726147,-73.975043,"730 E 12TH ST NEW YORK, NY 10009",...,48,1,0,0,0,0,0,0,0,0
4,NaN,NaN,NaN,THE STAR ACADEMY - P.S.63,310100010063,01M063,1,40.724404,-73.986360,"121 E 3RD ST NEW YORK, NY 10009",...,0,0,0,0,0,0,0,0,0,0
5,NaN,NaN,NaN,P.S. 064 ROBERT SIMON,310100010064,01M064,1,40.723747,-73.981602,"600 E 6TH ST NEW YORK, NY 10009",...,0,0,0,0,0,0,0,0,0,0
6,NaN,NaN,NaN,P.S. 110 FLORENCE NIGHTINGALE,310100010110,01M110,1,40.715293,-73.979927,"285 DELANCEY ST NEW YORK, NY 10002",...,0,0,0,0,0,0,0,0,0,0
7,NaN,NaN,NaN,P.S. 134 HENRIETTA SZOLD,310100010134,01M134,1,40.714301,-73.982966,"293 E BROADWAY NEW YORK, NY 10002",...,0,0,0,0,0,0,0,0,0,0
8,NaN,NaN,NaN,P.S. 140 NATHAN STRAUS,310100010140,01M140,1,40.719128,-73.983283,"123 RIDGE ST NEW YORK, NY 10002",...,61,2,0,0,1,0,0,0,0,1
9,NaN,NaN,NaN,P.S. 142 AMALIA CASTRO,310100010142,01M142,1,40.718230,-73.984082,"100 ATTORNEY ST NEW YORK, NY 10002",...,0,0,0,0,0,0,0,0,0,0
10,NaN,NaN,NaN,P.S. 184M SHUANG WEN,310100010184,01M184,1,40.711437,-73.985486,"327 CHERRY ST-2ND FL NEW YORK, NY 10002",...,48,28,0,0,0,25,0,0,2,21
11,NaN,NaN,NaN,P.S. 188 THE ISLAND SCHOOL,310100010188,01M188,1,40.719870,-73.977376,"442 E HOUSTON ST NEW YORK, NY 10002",...,50,3,0,0,3,0,0,0,0,3
12,NaN,NaN,NaN,ORCHARD COLLEGIATE ACADEMY,310100011292,01M292,1,40.713343,-73.986069,"220 HENRY ST NEW YORK, NY 10002",...,10,0,0,0,0,0,0,0,0,0
13,NaN,NaN,NaN,"TECHNOLOGY, ARTS, AND SCIENCES STUDIO",310100010301,01M301,1,40.729892,-73.984231,"185 1ST AVE NEW YORK, NY 10003",...,47,1,0,0,0,0,0,0,0,1
14,NaN,NaN,NaN,THE EAST VILLAGE COMMUNITY SCHOOL,310100010315,01M315,1,40.727726,-73.978382,"610 E 12TH ST NEW YORK, NY 10009",...,0,0,0,0,0,0,0,0,0,0
15,NaN,NaN,NaN,UNIVERSITY NEIGHBORHOOD MIDDLE SCHOOL,310100010332,01M332,1,40.713343,-73.986069,"220 HENRY ST NEW YORK, NY 10002",...,30,1,0,0,0,0,0,0,1,0
16,NaN,NaN,NaN,THE CHILDREN'S WORKSHOP SCHOOL,310100010361,01M361,1,40.727726,-73.978382,"610 E 12TH ST NEW YORK, NY 10009",...,0,0,0,0,0,0,0,0,0,0
17,NaN,NaN,NaN,NEIGHBORHOOD SCHOOL,310100010363,01M363,1,40.724404,-73.986360,"121 E 3RD ST NEW YORK, NY 10009",...,0,0,0,0,0,0,0,0,0,0
18,NaN,NaN,NaN,EARTH SCHOOL,310100010364,01M364,1,40.723747,-73.981602,"600 E 6TH ST NEW YORK, NY 10009",...,0,0,0,0,0,0,0,0,0,0
19,NaN,NaN,NaN,SCHOOL FOR GLOBAL LEADERS,310100010378,01M378,1,40.720185,-73.985957,"145 STANTON ST NEW YORK, NY 10002",...,74,5,0,0,2,3,0,0,0,4
20,NaN,NaN,NaN,EAST SIDE COMMUNITY SCHOOL,310100011450,01M450,1,40.729153,-73.982474,"420 E 12TH ST NEW YORK, NY 10009",...,56,9,0,1,2,4,2,0,0,5
21,NaN,NaN,NaN,"NEW EXPLORATIONS INTO SCIENCE, TECHNOLOGY AND ...",310100011539,01M539,1,40.719500,-73.979239,"111 COLUMBIA ST NEW YORK, NY 10002",...,0,0,0,0,0,0,0,0,0,0
22,NaN,NaN,NaN,TOMPKINS SQUARE MIDDLE SCHOOL,310100010839,01M839,1,40.723747,-73.981602,"600 E 6TH ST NEW YORK, NY 10009",...,59,5,0,0,2,1,0,0,0,2
23,NaN,NaN,NaN,P.S. 001 ALFRED E. SMITH,310200010001,02M001,2,40.712561,-73.997474,"8 HENRY ST NEW YORK, NY 10038",...,0,0,0,0,0,0,0,0,0,0
24,NaN,NaN,NaN,P.S. 002 MEYER LONDON,310200010002,02M002,2,40.712943,-73.991557,"122 HENRY ST NEW YORK, NY 10002",...,0,0,0,0,0,0,0,0,0,0
25,NaN,NaN,NaN,P.S. 003 CHARRETTE SCHOOL,310200010003,02M003,2,40.732632,-74.005947,"490 HUDSON ST NEW YORK, NY 10014",...,0,0,0,0,0,0,0,0,0,0
26,NaN,NaN,NaN,P.S. 006 LILLIE D. BLAKE,310200010006,02M006,2,40.777703,-73.960428,"45 E 81ST ST NEW YORK, NY 10028",...,0,0,0,0,0,0,0,0,0,0
27,NaN,NaN,NaN,P.S. 011 WILLIAM T. HARRIS,310200010011,02M011,2,40.744549,-74.000737,"320 W 21ST ST NEW YORK, NY 10011",...,0,0,0,0,0,0,0,0,0,0
28,NaN,NaN,NaN,P.S. 033 CHELSEA PREP,310200010033,02M033,2,40.748945,-74.000243,"281 9TH AVE NEW YORK, NY 10001",...,0,0,0,0,0,0,0,0,0,0
29,NaN,NaN,NaN,P.S. 040 AUGUSTUS SAINT-GAUDENS,310200010040,02M040,2,40.735118,-73.981697,"319 E 19TH ST NEW YORK, NY 10003",...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1242,NaN,x,NaN,SOUTH BRONX CLASSICAL CHARTER SCHOOL II,320700861035,84X364,7,40.808255,-73.925748,"333 E 135TH ST BRONX, NY 10454",...,0,0,0,0,0,0,0,0,0,0
1243,NaN,NaN,NaN,ICAHN CHARTER SCHOOL 2,321100860909,84X378,11,40.845031,-73.857976,"1640 BRONXDALE AVE BRONX, NY 10462",...,34,14,0,2,8,0,0,0,0,8
1244,NaN,x,NaN,SUCCESS ACADEMY CHARTER SCHOOL - BRONX 3,320800861044,84X380,8,40.827748,-73.913773,"1000 TELLER AVE BRONX, NY 10469",...,0,0,0,0,0,0,0,0,0,0
1245,NaN,x,NaN,BRILLA COLLEGE PREP CHARTER SCHOOL,320700861014,84X387,7,40.812806,-73.919302,"413 E 144TH ST BRONX, NY 10454",...,0,0,0,0,0,0,0,0,0,0
1246,NaN,NaN,NaN,BRONX GLOBAL LEARNING INSTITUTE FOR GIRLS CHAR...,320700860915,84X389,7,40.818739,-73.927164,"750 CONCOURSE VILLAGE W-LOWER LEVEL BRONX, NY ...",...,37,1,0,0,1,0,0,0,0,1
1247,NaN,NaN,NaN,MOTT HAVEN ACADEMY CHARTER SCHOOL,320700860925,84X394,7,40.806307,-73.920868,"170 BROWN PL BRONX, NY 10454",...,0,0,0,0,0,0,0,0,0,0
1248,NaN,NaN,NaN,BRONX COMMUNITY CHARTER SCHOOL,321000860914,84X398,10,40.872656,-73.874846,"3170 WEBSTER AVE BRONX, NY 10467",...,0,0,0,0,0,0,0,0,0,0
1249,NaN,NaN,NaN,BRONX CHARTER SCHOOL FOR CHILDREN,320700860852,84X407,7,40.812627,-73.919908,"388 WILLIS AVE BRONX, NY 10454",...,0,0,0,0,0,0,0,0,0,0
1250,NaN,NaN,NaN,BRONX ACADEMY OF PROMISE CHARTER SCHOOL,320900860913,84X419,9,40.839576,-73.919830,"1349 INWOOD AVE BRONX, NY 10452",...,53,2,0,1,0,0,0,0,0,2
1251,NaN,NaN,NaN,ICAHN CHARTER SCHOOL 3,321100860917,84X422,11,40.856635,-73.843042,"1500 PELHAM PKWY S BRONX, NY 10461",...,21,3,0,3,0,0,0,0,0,0
1252,NaN,x,NaN,ATMOSPHERE CHARTER SCHOOL,321000861075,84X460,10,40.875134,-73.910245,"22 MARBLE HILL AVE BRONX, NY 10463",...,0,0,0,0,0,0,0,0,0,0
1253,NaN,NaN,NaN,METROPOLITAN LIGHTHOUSE CHARTER SCHOOL,320900860962,84X461,9,40.834312,-73.930213,"180 W 165TH ST BRONX, NY 10452",...,0,0,0,0,0,0,0,0,0,0
1254,NaN,NaN,NaN,AMERICAN DREAM CHARTER SCHOOL,320700861062,84X471,7,40.809065,-73.917520,"510 E 141ST ST-4TH FL BRONX, NY 10454",...,0,0,0,0,0,0,0,0,0,0
1255,NaN,NaN,NaN,DR. RICHARD IZQUIERDO HEALTH AND SCIENCE CHART...,321200860965,84X482,12,40.827387,-73.900529,"800 HOME ST-RM 205 BRONX, NY 10456",...,147,1,0,0,1,0,0,0,0,1
1256,NaN,NaN,NaN,GIRLS PREPARATORY CHARTER SCHOOL OF THE BRONX,320800860940,84X487,8,40.815971,-73.901686,"681 KELLY ST-RM 205 BRONX, NY 10455",...,0,0,0,0,0,0,0,0,0,0
1257,NaN,NaN,NaN,THE EQUALITY CHARTER SCHOOL,321100860956,84X488,11,40.864136,-73.823960,"4140 HUTCHINSON RIVER PKWY E BRONX, NY 10475",...,88,4,0,2,0,0,0,0,0,2
1258,NaN,NaN,NaN,ACADEMIC LEADERSHIP CHARTER SCHOOL,320700860957,84X491,7,40.807731,-73.912768,"677 E 141ST ST BRONX, NY 10454",...,0,0,0,0,0,0,0,0,0,0
1259,NaN,x,NaN,SOUTH BRONX EARLY COLLEGE ACADEMY CHARTER SCHOOL,320700861068,84X492,7,40.808913,-73.921746,"423 E 138TH ST-7TH FL BRONX, NY 10454",...,0,0,0,0,0,0,0,0,0,0
1260,NaN,NaN,NaN,SUCCESS ACADEMY CHARTER SCHOOL - BRONX 1,320700860981,84X493,7,40.813660,-73.925999,"339 MORRIS AVE-2ND FL BRONX, NY 10451",...,0,0,0,0,0,0,0,0,0,0
1261,NaN,NaN,NaN,SUCCESS ACADEMY CHARTER SCHOOL - BRONX 2,320900860980,84X494,9,40.835973,-73.904838,"450 ST PAUL'S PL-5TH FL BRONX, NY 10456",...,0,0,0,0,0,0,0,0,0,0
1262,NaN,NaN,NaN,ICAHN CHARTER SCHOOL 4,321100860948,84X496,11,40.856635,-73.843042,"1500 PELHAM PKWY SOUTH BRONX, NY 10461",...,30,23,0,20,3,0,0,0,0,17
1263,NaN,NaN,NaN,ICAHN CHARTER SCHOOL 5,321100860982,84X538,11,40.856635,-73.843042,"1500 PELHAM PKWY S BRONX, NY 10461",...,0,0,0,0,0,0,0,0,0,0
1264,NaN,NaN,NaN,NEW YORK CITY MONTESSORI CHARTER SCHOOL,320700861005,84X554,7,40.808913,-73.921746,"423 E 138TH ST BRONX, NY 10454",...,0,0,0,0,0,0,0,0,0,0
1265,NaN,NaN,NaN,BRONX PREPARATORY CHARTER SCHOOL,320900860807,84X703,9,40.839046,-73.900190,"3872 3RD AVE BRONX, NY 10457",...,86,11,0,0,4,0,0,0,0,10
1266,NaN,NaN,NaN,KIPP ACADEMY CHARTER SCHOOL,320700860820,84X704,7,40.816194,-73.926169,"201 E 144TH ST BRONX, NY 10451",...,69,15,0,6,9,0,0,0,0,14
1267,NaN,NaN,NaN,FAMILY LIFE ACADEMY CHARTER SCHOOL,320900860839,84X705,9,40.840277,-73.918654,"14 W 170TH ST BRONX, NY 10452",...,47,1,0,1,0,0,0,0,0,1
1268,NaN,NaN,NaN,HARRIET TUBMAN CHARTER SCHOOL,320900860823,84X706,9,40.832272,-73.905817,"3565 3RD AVE BRONX, NY 10456",...,58,9,0,8,1,0,0,0,0,5
1269,NaN,NaN,NaN,ICAHN CHARTER SCHOOL,320900860835,84X717,9,40.839176,-73.904982,"1525 BROOK AVE BRONX, NY 10457",...,31,7,0,3,4,0,0,0,0,5
1270,NaN,NaN,NaN,BRONX CHARTER SCHOOL FOR BETTER LEARNING,321100860855,84X718,11,40.888739,-73.847787,"3740 BAYCHESTER AVE ANNEX BRONX, NY 10466",...,0,0,0,0,0,0,0,0,0,0
1271,NaN,NaN,NaN,BRONX CHARTER SCHOOL FOR THE ARTS,320800860846,84X730,8,40.821798,-73.886463,"950 LONGFELLOW AVE BRONX, NY 10474",...,0,0,0,0,0,0,0,0,0,0

In [10]:
school.size()

TypeError: 'numpy.int64' object is not callable

In [7]:
shsat

,DBN,School name,Year of SHST,Grade level,Enrollment on 10/31,Number of students who registered for the SHSAT,Number of students who took the SHSAT
0,05M046,P.S. 046 Arthur Tappan,2013,8,91,31,14
1,05M046,P.S. 046 Arthur Tappan,2014,8,95,26,7
2,05M046,P.S. 046 Arthur Tappan,2015,8,73,21,10
3,05M046,P.S. 046 Arthur Tappan,2016,8,56,20,8
4,05M123,P.S. 123 Mahalia Jackson,2013,8,62,31,14
5,05M123,P.S. 123 Mahalia Jackson,2014,8,62,25,13
6,05M123,P.S. 123 Mahalia Jackson,2015,8,62,12,5
7,05M123,P.S. 123 Mahalia Jackson,2016,8,55,16,5
8,05M129,P.S. 129 John H. Finley,2013,8,84,58,14
9,05M129,P.S. 129 John H. Finley,2014,8,55,23,12
10,05M129,P.S. 129 John H. Finley,2015,8,63,12,10
11,05M129,P.S. 129 John H. Finley,2016,8,50,15,12
12,05M148,Eagle Academy for Young Men of Harlem,2015,8,76,5,5
13,05M148,Eagle Academy for Young Men of Harlem,2016,8,60,7,6
14,05M148,Eagle Academy for Young Men of Harlem,2016,9,86,0,0
15,05M157,The Urban Assembly School for Global Commerce,2013,9,82,3,1
16,05M157,The Urban Assembly School for Global Commerce,2014,9,103,2,1
17,05M157,The Urban Assembly School for Global Commerce,2015,9,60,2,1
18,05M157,The Urban Assembly School for Global Commerce,2016,9,64,0,0
19,05M161,P.S. 161 Pedro Albizu Campos,2013,8,118,10,5
20,05M161,P.S. 161 Pedro Albizu Campos,2014,8,123,26,17
21,05M161,P.S. 161 Pedro Albizu Campos,2015,8,120,28,22
22,05M161,P.S. 161 Pedro Albizu Campos,2016,8,114,18,11
23,05M286,I.S. M286 Renaissance Leadership Academy,2013,8,60,27,13
24,05M286,I.S. M286 Renaissance Leadership Academy,2014,8,67,44,9
25,05M286,I.S. M286 Renaissance Leadership Academy,2015,8,38,38,6
26,05M286,Urban Assembly Academy for Future Leaders,2016,8,93,90,25
27,05M302,KAPPA IV,2013,8,54,28,15
28,05M302,KAPPA IV,2014,8,86,25,13
29,05M302,KAPPA IV,2015,8,62,18,6
...,...,...,...,...,...,...,...
110,84M350,Democracy Prep Charter School,2015,8,112,31,24
111,84M350,Democracy Prep Charter School,2016,8,130,36,24
112,84M350,Democracy Prep Charter School,2013,9,124,0,0
113,84M350,Democracy Prep Charter School,2014,9,122,0,0
114,84M350,Democracy Prep Charter School,2015,9,104,2,2
115,84M350,Democracy Prep Charter School,2016,9,113,0,0
116,84M384,Success Academy Charter School - Harlem 2,2016,8,70,34,32
117,84M388,St. HOPE Leadership Academy Charter School,2013,8,68,27,24
118,84M388,St. HOPE Leadership Academy Charter School,2014,8,76,26,20
119,84M388,St. HOPE Leadership Academy Charter School,2015,8,76,13,10
120,84M388,St. HOPE Leadership Academy Charter School,2016,8,85,18,14
121,84M481,Democracy Prep Harlem Charter School,2013,8,117,21,14
122,84M481,Democracy Prep Harlem Charter School,2014,8,114,26,15
123,84M481,Democracy Prep Harlem Charter School,2015,8,107,24,22
124,84M481,Democracy Prep Harlem Charter School,2016,8,110,17,12
125,84M481,Democracy Prep Harlem Charter School,2013,9,110,0,0
126,84M481,Democracy Prep Harlem Charter School,2014,9,119,0,0
127,84M481,Democracy Prep Harlem Charter School,2015,9,106,1,1
128,84M481,Democracy Prep Harlem Charter School,2016,9,113,0,0
129,84M709,Harlem Village Academy Charter School,2013,8,68,12,8
130,84M709,Harlem Village Academy Charter School,2014,8,65,20,14
131,84M709,Harlem Village Academy Charter School,2015,8,53,26,19
132,84M709,Harlem Village Academy Charter School,2016,8,66,18,16
133,84M709,Harlem Village Academy Charter School,2014,9,61,1,1
134,84M709,Harlem Village Academy Charter School,2015,9,45,2,1
135,84M709,Harlem Village Academy Charter School,2016,9,42,1,1
136,84M726,KIPP STAR College Prep Charter School,2013,8,75,74,29
137,84M726,KIPP STAR College Prep Charter School,2014,8,71,74,19
138,84M726,KIPP STAR College Prep Charter School,2015,8,84,84,29
139,84M726,KIPP STAR College Prep Charter School,2016,8,62,60,19